# Generated by Django 6.0.7 on 2026-07-12 06:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scan_type', models.CharField(max_length=50)),
                ('image', models.ImageField(blank=True, null=True, upload_to='reports/')),
                ('ai_prediction', models.CharField(blank=True, default='', max_length=255)),
                ('confidence', models.FloatField(default=0)),
                ('severity', models.CharField(default='Pending', max_length=50)),
                ('recommendation', models.TextField(blank=True, default='')),
                ('status', models.CharField(default='Pending', max_length=30)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
